### A Pluto.jl notebook ###
# v0.19.32

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
end

# ╔═╡ 7b9e2ba5-3b8f-40a8-892d-862a361e0b93
using JuMP

# ╔═╡ 8f50ab05-0053-46c5-97bc-751982cfc5f7
using SankeyPlots

# ╔═╡ 1592cd26-4c3a-4171-b306-e187b43f7258
using Dates

# ╔═╡ a66678a3-59ab-43cc-8a0d-fdeb0770f3e6
using PlutoTeachingTools, ShortCodes, PlutoUI, Plots

# ╔═╡ f09d1eda-bfcb-4ab9-b1ce-2f59fd9747c9
ChooseDisplayMode()

# ╔═╡ 60119a67-1aa0-4c7e-8514-45420e576d83
md"""
# ECONOMIC EVALUATION OF GREEN HYDROGEN AND SYNTHETIC FUEL PRODUCTION WITH DC MICROGRID INTEGRATION
"""

# ╔═╡ c3968558-28ee-49f1-9e87-d2d88f166abb


# ╔═╡ 394b7f89-7259-4339-b6c9-df9e82fba253
md"""

$\text{ \:Ricardo Luís\quad\:\: João Gomes\quad\:\: Jaime Puna\quad\:\: João Lagarto\quad\:\: Teodoro Trindade\quad\:\: Jorge Sousa\quad\:\: Armando Cordeiro}$
"""

# ╔═╡ 6a4a8025-9184-4e93-a80e-eddea4857658


# ╔═╡ c5c096c9-36d2-49f3-9ce1-853eabf1aaf0


# ╔═╡ 2ba7396c-20f4-4995-a609-7794e34c1648


# ╔═╡ 7d086988-14ac-47fb-87dd-ed0235fa13d3

eeic_url="https://eeic2023.isel.pt/wp-content/uploads/2023/06/EEIC_2023_logo.png";

# ╔═╡ 0323250e-3146-45ce-a87c-d8e53fa25938
TwoColumn(md"$(Resource(eeic_url, :height => 60))", md" $\textbf{\color{green}{Energy Economics Int. Conf.}, } \rm 7^{th} \text{APEEN Annual Conf., ISEL, Lisbon, November 2-3, 2023}$") 

# ╔═╡ e7002bff-26cc-4f1d-80cb-89da0adcb7dd


# ╔═╡ 0d054678-b051-4abe-a77d-6af8978edb28
md"""
# OBJECTIVES
"""

# ╔═╡ bf816930-4a28-11ed-18ae-ff9176a0e53f
md"""
# SOLAR H2
**Integration of Synthesis Gas Production with Renewable Energy within a DC Microgrid**

An existing electrolytic system is to be connected to a DC microgrid in
order to use electric energy generated in photovoltaic solar panels to
obtain hydrogen/synthesis gas to be stored further and converted to
liquid fuels, thus avoiding the actual variability of electric energy
generated by renewable sources.

"""

# ╔═╡ 442f8172-c833-42e8-9f58-d4674a2fb070


# ╔═╡ 1ef6b34b-edd1-464b-a275-f53a30f21254
md"""
## Research team

- **João Fernando Pereira Gomes**
- Jaime Filipe Borges Puna
- Jorge Alberto Mendes de Sousa
- João Hermínio Ninitas Lagarto
- Ricardo Jorge Ferreira Luis
- Armando José Leitão Cordeiro
- Teodoro José Pereira Trindade
- José João Campos Rodrigues

**Other collaborators:**
- Derik Soares (MSc student)
- Pedro Fonte (MSc supervisor)
- Paulo Almeida (Lab support)

"""

# ╔═╡ d7328acf-75dd-4a74-93e3-56a493b8f72e
md"""
## Workbench draft
"""

# ╔═╡ ca251372-9a6f-409c-aa17-1349fa142f1a
html"""
<iframe frameborder="0" style="width:100%;height:700px;" src="https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=solar.H2.drawio#R7V3bcuI6Fv2aVM08hLJly5fHBMJ0T6XrpE7XuT11OViA5xiLMSaB%2Fvoj2TLYWwIbYgFJ6KruxrKQL2tr7aWtLXFj9Wer%2F6TBfPqNhiS%2BQUa4urEGNwiZyEDsP16yLko8zy8KJmkUikrbgu%2FRTyIKDVG6jEKyqFXMKI2zaF4vHNEkIaOsVhakKX2tVxvTuH7VeTAhUsH3URDLpX9EYTYVpabjb098IdFkKi7tIbc4MQvKyuJJFtMgpK%2BVIuvhxuqnlGbFp9mqT2L%2B8sr3UnxvuOPs5sZSkmRtvvDrV%2FPr09N%2Ff%2Fv6q%2BEGLk3x78HwVtzsIluXD0xC9vzikKbZlE5oEsQP29L7lC6TkPBWDXa0rfNI6ZwVmqzwfyTL1gLMYJlRVjTNZrE4S1ZR9qf4Ov%2F8F%2F%2Fcw%2BJosKqcGqwrB08kjWYkI2lZlmTp%2Bs%2ByUX5QaYkfbpvKj9bVI9jYmCaZuGPTySuFd9x%2B2HFCE1KUDKM4FvWLF8ff1k48RNGCLtMR2QNCaddBOiHZnnpoYzWsuxHK7j5ds%2B%2BlJA6y6KV%2BH4Gw%2B8mm3tY02AdhHQdYimj3JYiX4kqS6byQNItY13kMnkn8RBdRFtGEnXqmWUZn7J1tugB%2FgWGwmG6sKIijCa86Yi%2BPQ3I%2FZm%2B6T2Oa5k1bRv6nbkbl5e7EdzNufveLLKV%2Fb%2FqqVVx1zu9wtppwjuqRmBFFyr%2FZm0WLEXv2ICF0uejNaEL54Y%2FnIGN3sc5tPQvEU9z6W9j5pclqP%2FAyUOILtisYQVCiZQouea0QjCHqTCvc4hiasEVXbDVha58dW0vC1kS%2FS%2FCyJ87qCEioQUhmURgW%2FoAsop%2FBc94Uf41zGiVZ%2Fhj4%2FgYPeFvMBSwEt25gLC1AsGvVKMoiQMkd4IMxrvc9S8bHVsCDdMFjX%2BHZA49dYnEueLxmZpSFQgWmulaSNIYQQqUoOlYIyby4kUZGz93Iob9qakitjc4gayxLbRMVzLEC87KstfwRV3ji9l9hbAd4YxfYUvGc4ltVfQ0a8qBbN0BDxYuQGmLGE6wr1UT%2F3HnDvqW%2BztbMixa3Rr95p8f3A19rP9hrv0iT%2FV64XWJUhxlDc2prl6ZhNLTUkWHCDoBPYZiOwjCdmDvLMHqpGajz%2FyUfat9zX3or3OcdqxGTcbY9yz5NxP95K88pLGG3mTddloJuULf012mUke%2FzICfKVyZR692iuSN04FQdwHDIk52qaam8qq3LrZbRHQVs%2FJUoceMnbguZwmEznflKhg3ZTDwZ%2Fxr0%2F12Bq2hyB16ytGqrf9pLMJUV7GZEWw%2FsG3%2FUNBSxtKHeIoZwpBexd4eDmoJBimBUqcfUCqzeSVG3oslp6Zyci9JMcPTa1jdhEzRktnNNXXkPUxX56ISHLCMnorsrESHHBzERp2VMRB8RyUGRfUREWb2DhnWbQHHBROW0hrfHwzeTx7k6u7nLjxzc2VFDQ7o7uxxruaLeFnXb97tBXWpIN%2Bp4J8VfRwgrIPQvaISgGth9YK3YHE0TdtyoDMuKF0Mldkdi0T%2BzVnR3Esl1zNqRVEQuiP%2B7Zx%2BzqmYAukAd5wOEXq%2FH%2FkXO1QI2rsgCIvHcgwXsyY6nMUfmDVkx9ckgt2E2aBsnr4XJN25thyc7NNtFJWdVU%2Fh1f8dbHi3Tl9xgzG4DJaWsbPSHeEeo5DCvdmgwHAMmM2F2FqjvlolyR9b3ThBrL195hQuf5LnqBkEbLOZFnt44WnG7aKFwQb6IExjGeCy%2BWSkf539U5mm5htHvl9cSt1oGI9%2BW7gFQbumuTDj07c5fqWbquhjuDH97eGQn%2Bw%2BPj7vGOacdVXVxteWcMwjlTrqH%2Fv7j3Q7grIsbv6HDYv1HBFsq%2FgiEXpTppWi%2FIz0%2BQtPaV51v%2FFW3Du%2FI8RdsR1eCg3QdfALXhi7MXBt030c2Vw%2F6VHykvQJW1JX3AK%2FjncJeVTMYHU5c3bK%2F2Pjy832PR3Vk%2BLoeYCf33ANUJM9rPKV0kgazWZ72iYxBnz8ifWXvl6G2nM%2FjtQYEc4nVGX5dZZRKbKJAC8toQSfZHVryfEQOT0yDcCGhon0wNTYCywjkwRQY0VfO3A%2Fc4oz2wZTltOtZ%2BkZTSBXz%2FbQqFl%2BSLMDOkaoAqEvTAbdysCroeqIBHZZ0%2FsG16EUZnemCJo7Vosi8OKuTA0fFxFTunb5FIy4pWAuXr%2Fw6Ug62bffq6COskHr%2BKaVe2TAQD8McoxFN8gdOPw9GyLLrTsFSyDvVgiF9CMlxrxyhu0%2BKkANWdF0AQoelgR28pmtP4pe5d2lL45xdXbmHAfHGI5VCd0YeeR4f5IcvfDGMWWqi0orggr%2FWi7RAMopjuW%2F0wy1v2N8%2FnefDNTr1%2BnqCSJY8FP1SBnwWy%2BdNSKgSBKoU%2F%2FJ5SMwHYJacdj4O05cddyiHvYnCMPFCW0VhHnq2nOoS2e2y2Oaku%2Fa015x1579LfnRgbtyx%2FOiWhtX1Ita6KnDsBnoEwydQXxM9yjH2h3x7CRqvfyo03OVNC8MVmcp5YaQwS33zwpYcUTvA53wel2NjYPGGIhh6Wp%2BjeS%2BEA3yO%2Bxanw5OEPGUW23D4gH2%2F4nQO2ZehQ6djo3fhdBwwE%2BYduzDIA%2BLXhexz9uCYJQfHfrmylkIog%2Bxd7LgSa3mnJK3Sks5FWsdzT13wGifjnrMuFXGg0zuSUUA7UrigIxUrXQYBg9WgSm05wHgXfaKAIlhO6Cgk7WkZBjUzzPalmF2MDHSktcAAlKtKlFANFbRtXGefOU77llgF6j5YcS5Kxqbfs0B0AeqzA9YCw7Yk0dgRNfPb9tSX0kvPLbYWeAd0AHf4cA2rpwh6qgjBtXQRghyu%2FkayIJaXDEzXYRqFRINTvMgcN9vHYKbaVez145wyy832Za4%2B4cbSBwSL96yEE5k1zRs7qHS8wqO0pfoWMr0MozWHCFy16Zxm02gsD7%2Bu42aV%2BrJA%2F0Uy2ap8vL5Fry3EV4duDKlR22wjXbbQarWfbaEBdrsKw%2BIeAlsGq7Z0tu2eq%2BBX29cGkOwMHxKSTta7F9B1szBvMQ%2BSsmyR0ZT%2FfkKl91bOtlxN92E7NXZc6JbbThxjbWbTYuI4muW%2FiVFFRBQNotmEXTaOGEUPR3E0%2FxGkzFSGE8JMjwux4VO8nPwwkbdif3vzZKLqxDINqDpvK4KoSN%2BulK8HphoVO1Cr4gvalBSWQ89XxPYi5p8ZMUcWPRJitV0R9kYx2sQt2u3EcNINJrT9WErpjZv3ffDVVnOqzHGwzODYbcUxsG5TVywbTDgjt2EDCpApYjZkuEn10QmiMY4cLO9mmWSezlvkw0O59VFXUHYVaEb1KUKn5SIvfXSNJBtRLZ8sflmGJtHoplispwHBi4wuYRBGVS%2FL6ya4xA63P4hWkMD2Z%2BWsh38A"></iframe>
"""

# ╔═╡ dfb56aac-626b-4655-9321-99ab2fc74cfe
md"""
Fig.1: Workbench scheme. **Note:** In practise the equipment not allow a water closed circuit and O₂ storage.
"""

# ╔═╡ 9c694aa7-2970-4de2-ada8-7ac34b4f37a2


# ╔═╡ 2b376666-65bc-47f7-90a7-35decb87078a
md"""
# Fuel cell U-I curve (lab test)
"""

# ╔═╡ bbeb147a-2cb2-4177-958f-4d6b171cbb28
md"""
## Measured values
"""

# ╔═╡ e85d6f57-1d76-475f-ade0-fe85a82bc5ca
U = [43.0; 41.0; 39.9; 38.9; 38.0; 37.2; 36.4; 35.7; 35.4; 35.0; 34.7; 34.4; 34.0; 33.7];

# ╔═╡ 0314ef45-6b1c-4738-aad1-e26e3cdfaa66
I = [0.9; 1.7; 2.5; 3.2; 4.0; 4.6; 5.2; 5.9; 6.6; 7.3; 8.0; 8.6; 9.3; 10.0];

# ╔═╡ dde18063-a566-4ba5-a918-5242eac54430
P=U.*I

# ╔═╡ a9694e3c-b208-4021-908e-f79ac3fd813a
md"""
## Results
"""

# ╔═╡ 56bf6aa7-37e3-4ef8-afd7-c282289a8852
begin
	scatter(I, U, 
		ylabel="Voltage (V)", xlabel="Current (A)",
		ylims=(0,50), xlim=(0,12), label=:none)
	plot!(I, U, lc=:blue, lw=2, label="U(I)", legend=:topleft)
	
	scatter!(twinx(), I, P, xlim=(0,12), ylims=(0,400), mc=:green, 
		label=:none, ylabel="Power (W)")
	plot!(twinx(), I, P, xlim=(0,12), ylims=(0,400), 
		lc=:green, lw=2, label="P(I)", legend=:topright)
end

# ╔═╡ 73cdec6e-71cb-4c5a-9b2f-cee0f90a4812
md"""
Fig.2: Fuel cell load test results.
"""

# ╔═╡ 5c4efd0e-3db4-419e-b125-fa7a0645cef2


# ╔═╡ bf16906f-f285-471d-97ed-6dc359404bf3
md"""
# DC Microgrid (System Setup)
"""

# ╔═╡ af291ea0-b03c-4d77-aa75-670cd07a161d
md"""
## Workbench overview 
"""

# ╔═╡ e5ad7e3a-f912-45e9-9b15-add18ec3195a
md"""
$(Resource("https://i.imgur.com/zoHNvD2.jpg", :width => 825))

Fig.3: Solar-H2 workbench view.

\
$(Resource("https://i.imgur.com/ukdMRKF.jpg", :width => 205))
$(Resource("https://i.imgur.com/L2iXxev.jpg", :width => 205)) 
$(Resource("https://i.imgur.com/XaVSzQT.jpg", :width => 205))
$(Resource("https://i.imgur.com/tXFFpj5.jpg", :width => 205))

Fig.4: Output parameters of the electroliser.

\
$(Resource("https://i.imgur.com/DVEhs5V.jpg", :width => 300))

Fig.5: Hydrogen storage with metal hydride canisters.

\
$(Resource("https://i.imgur.com/xD9byhx.jpg", :width => 600))

Fig.6: Fuel cell.

\
$(Resource("https://i.imgur.com/ZWnpMRT.jpg", :width => 600))

Fig.7: DC-DC converter of fuel cell, control unit, lead-acid bateries (24V) and sine wave inverter.

\
$(Resource("https://i.imgur.com/QJ6g4So.jpg", :width => 300))

Fig.8: DC programable power source/electronic load.

\
$(Resource("https://i.imgur.com/Ga1Eug4.png", :width => 400))
$(Resource("https://i.imgur.com/uYZobfq.png", :width => 400))

Fig.9: Monitoring of the DC-DC converter and fuel cell.

\
$(Resource("https://i.imgur.com/dysAoww.png", :width => 800))

Fig.10: Monitoting the DC programable power source/electronic load.
"""

# ╔═╡ e1d04a77-a5d1-456d-8af5-f3e46678e0a1


# ╔═╡ 62e09a4f-3beb-4c2a-844f-76b32db8a9a8
md"""
## Equipment
"""

# ╔═╡ 2b48bce0-8278-4542-9214-b6b6aa05857a
Foldable("Electroliser", md"""Manufacturer: Schmidlin-DBS AG; Model: NM-H2 500

Main specs:

 $\begin{align}
\textrm{Electrolysis cell} &= \textrm{Solid polymer membrane type} \\
\rm{H_2 \:purity} &= {\:\: >99.9999\%} \\
\textrm{Flow rate} &= \textrm{0-500cc/min @ STP} \\
\textrm{Outlet pressure} &= \textrm{Min. 1.4 bar; Max. 10.7 bar} \\
\textrm{Power consumption} &= \textrm{300VA} \\
\textrm{Input voltage} &= \textrm{240V} (\pm 10\%) \textrm{, 50Hz} \\
\textrm{Flow rate} &= \textrm{0-500cc/min @ STP} \\
\end{align}$

📂[Documentation](https://drive.google.com/drive/folders/1HJW1k-y-0plMwe_fo3eojvj1xva3ZOfU?usp=share_link)""")

# ╔═╡ 25e7c7f4-c434-4ef7-a9dd-e10de282d3b8
Foldable("Metal hydride", md"""Manufacturer: Ovonic Hydrogen Systems LLC; Model: 85G555B

Main specs (to confirm):

 $\begin{align}
\rm{H_2 \: content} &= \textrm{32scf (900sl)} \\
\textrm{Rated discharge} &= \textrm{6.0slpm/600W} \\
\textrm{Re-filling} &= \textrm{Charges approx 8 hours at 250psig in flowing ambient air} \\
\textrm{Operating temperature} &= \textrm{0 - 75ºC} \\
\textrm{Storage temperature} &= \textrm{-29 - 54ºC} \\
\end{align}$

🔗[Link](https://www.fuelcell.sg/hydrogen.php)
""")

# ╔═╡ 90dffbb7-8055-4d69-ac85-a2c7b511f024
Foldable("Fuel cell", md"""Manufacturer: Ballard; Mode: Nexaᵀᴹ 310-0027

Main specs:

 $\begin{align}
\textrm{Rated power} &= \textrm{1200W, but presents high wear! Works up to } \approx \rm{300W} \\
\textrm{Operating voltage range} &= \textrm{22V - 50V} \\
\textrm{Start-up Time} &= \textrm{2 min.} \\
\textrm{Allowable range of inlet supply pressure} &= \textrm{70 – 1720 kPa(g)} \\
\textrm{Maximum fuel consumption at Rated Power} &= \textrm{ <18.5 SLPM} \\
\end{align}$

📂[Documentation](https://drive.google.com/drive/folders/1bK7JzYfldKBmCfikPEL21nStzYOQBARg?usp=share_link)""")

# ╔═╡ 5b87a2e7-4c24-4504-b623-8647539780c5
Foldable("DC-DC converter", md"""Manufacturer: [isle Steuerungstechnik und Leistungselektronik GmbH](http://www.isle-ilmenau.de/); Model: BSZ-PG 1200

Main specs:

 $\begin{align}
\textrm{Nominal output voltage; range} &= \textrm{24V; 22V-30V} \\
\textrm{Accuracy of output voltage} &= \textrm{2\%} \\
\textrm{Nominal output current; Maximum} &= \textrm{50A; 55A} \\
\textrm{Maximum output current ripple} &= \textrm{2\%} \\
\textrm{Maximum output power} &= \textrm{1200W} \\
\textrm{Operating input voltage range} &= \textrm{26V-48V} \\
\end{align}$

📂[Documentation/software](https://drive.google.com/drive/folders/15fe-onP6MJtuxihrE-uSLHvPiVV_R25F?usp=share_link)""")

# ╔═╡ 958392cf-a0c1-4feb-bdcd-9a3dd4efb8fd
Foldable("Lead-acid batteries", md"""Manufacturer: EnergiVm; Model: MVH12180M5

Main specs:

 $\begin{align}
\textrm{Nominal voltage} &= \textrm{12V} \\
\textrm{Nominal capacity} &= \textrm{18Ah} \\
\textrm{Internal resistance} &= \textrm{15m}\Omega \\
\textrm{Constant voltage charge (standby)} &= {13.5V} \sim \textrm{13.8V @ 25ºC} \\
\end{align}$

📂[Documentation](https://drive.google.com/drive/folders/1fzK5BpT6PaC4rZz3CpVc-Z_8KZyNiu9D?usp=share_link) """)

# ╔═╡ 3214f857-a5d0-448b-aa77-5ccef8ae0f31
Foldable("DC programmable power source", md"""Manufacturer: [Aim-TTi](https://www.aimtti.com/product-category/dc-power-supplies); Model: QPX750SP

Main specs: $\rm{80V; 50A; 750W}$

📂[Documentation/software](https://drive.google.com/drive/folders/1uSv1T9hKnCtbbOrZOear5VKjNpEUbeZX?usp=share_link)""")

# ╔═╡ 4dc0b911-4ffc-4924-81f7-8a015ed5937a
Foldable("DC programmable electronic load", md"""Manufacturer: [Aim-TTi](https://www.aimtti.com/product-category/electronic-loads); Model: LD400P

Main specs: $\rm{80V; 80A; 400W}$

📂[Documentation/software](https://drive.google.com/drive/folders/1v2d7SgiWkivlb6yyQ7NP6zrg3V5QN6PK?usp=share_link)""")

# ╔═╡ f394202b-de77-4f89-b79d-38747f8e77d3
Foldable("Sine wave inverter", md"""Manufacturer: COTEK; Model: SK1500-224

Main specs:

 $\begin{align}
\textrm{AC voltage; frequency} &= \textrm{220/230/240V; 50/60Hz} \\
\textrm{Rated power; surge power} &= \textrm{1500W; 3000W} \\
\textrm{Waveform} &= \textrm{THD\:<\:3\%} \\
\textrm{Power factor allowed} &= {\cos\varphi\: (-90\degree \:\:\sim\:\: +90\degree)} \\
\end{align}$

📂[Documentation](https://drive.google.com/drive/folders/1CNDKj3qoPkAfkpzkGLxo4OTtPIyDiQYp?usp=share_link)
""")

# ╔═╡ d861716d-b0c4-40f9-9fa2-5c8539480a18


# ╔═╡ 9d28361c-d3b4-44af-9a9c-d13d4f911f1f


# ╔═╡ f8c559c3-8064-4f3c-a767-510eebc96d85


# ╔═╡ 88dfac9b-737d-4057-a1ea-db6ad61e22ef
md"""
# Study
"""

# ╔═╡ 5a17bbf9-514f-4b2e-b8db-144c66f4af07
md"""
## Photovoltaic Conversion of Solar Energy
"""

# ╔═╡ 18f78524-7836-4719-9c39-6999a3789125
DOI("10.3390/su7032644")

# ╔═╡ 0d674fc4-d0a8-45a5-9c38-efd6e340fc54
md"""
[mit-c25.netlify.app/notebooks/10\_climate\_science.html](https://mit-c25.netlify.app/notebooks/10_climate_science.html)
"""

# ╔═╡ 1bda23b8-b8c0-4ad2-83c8-1b322cf4a119
md"""
[Global Solar Atlas](https://globalsolaratlas.info/map?s=38.757296,-9.117966&m=site&c=38.703463,-9.148178,11)
"""

# ╔═╡ a0cf81c4-a54e-4ee8-8813-3c1e989335cb


# ╔═╡ f9e7768e-28a0-4c3a-b3df-5930a0ae097b
md"""
The model of extraterrestrial solar radiation, $G_0$, for a certain location could be expressed by
the relation:

$$G_0=\frac{24}{\pi} S \left[ 1+0.33
\cos\left(\frac{2\pi n}{365}\right) \right](\cos \phi \cos \delta \sin \omega + \omega \sin \phi \sin \delta) \quad\quad [\rm W/m^2]$$

where:
-  $S$ is the solar constant;
-  $n$ is the days’ number of the year;
-  $\phi$ is the latitude of the considered location;
-  $\delta$ represents the declination of the Earth;
-  $\omega$ is the solar horary angle.
"""

# ╔═╡ c37c265d-57f9-41ec-9a85-f2cb90856cbf
S = 1361 # W/m²

# ╔═╡ 00ce55cc-27fa-4540-9983-e1d696bad2d1
ϕ = 44.3  # in degrees, example of Craiova, Romania

# ╔═╡ bfe09a62-2369-4f10-8898-1adfb46b275e
δ = 23.4  # in degrees

# ╔═╡ 12345a52-fde5-41eb-ac49-21eb5ac2ee16


# ╔═╡ 3bad4c86-867d-4e9c-99c5-9b316542a765
begin
	h = today()
	n = Dates.dayofyear(h)
	h, n
end

# ╔═╡ 1d3f9163-d52f-4f50-baf3-a24d327e7f7c


# ╔═╡ c666b7b1-d810-43b3-85ee-77517f6ca409
md"""
One hour the sun travels in the sky an angle equal to 15°, and its position at any
time $T$ (hours) can be expressed by the relationship below:

$$\omega=15(12-T)$$

"""

# ╔═╡ 92a0edf6-8f8b-4daf-a3a3-135ff12fd492
md"""
Horary angles of sunrise and sunset $$(\alpha_s=0)$$, with $$\alpha_s$$  as the sun elevation angle.

$$\omega_s=\pm \cos^{-1}(-\tan \phi \:\tan \delta)$$

"""

# ╔═╡ 3f88433b-6256-428d-983b-e6fc6128efb5
ωₛ = acos(-tand(ϕ)*tand(δ))*180/π  # in degrees

# ╔═╡ 5ad49800-5dc0-4642-b374-afccb139cf83
md"""
[Solar irradiance - Wikipedia](https://en.wikipedia.org/wiki/Solar_irradiance)

[Applied Sciences | Free Full-Text | M-Shape PV Arrangement for Improving Solar Power Generation Efficiency](https://www.mdpi.com/2076-3417/10/2/537)
"""

# ╔═╡ d572be50-93f1-4574-9afe-4320dfe517e2


# ╔═╡ 191009da-e7c3-484e-b15c-755012216902
md"""
## Jump
"""

# ╔═╡ 75e0a7e1-fa8b-4368-bfbd-5cd42bbb90ef
md"""
Julia book for Jump:
- [Julia Programming for Operations Research, 2nd Ed.](https://www.chkwon.net/julia/)
"""

# ╔═╡ 8328d2d8-9ad5-4cf9-8006-30bf8b192e3e
md"""
[JuMPTutorials.jl · GitHub](https://github.com/jump-dev/JuMPTutorials.jl/blob/master/notebook/introduction/getting_started_with_JuMP.ipynb)
"""

# ╔═╡ 9477af88-edf1-4403-be5d-0fabc7e68c5a
md"""
[(1520) Tutoriais de Julia em Português - JuMP.jl parte 5 - Não linear inteira mista - YouTube](https://www.youtube.com/watch?v=wCKodtczy1I)
"""

# ╔═╡ 943e4e34-0e34-431b-8d5b-e6982af15e73
md"""
[gdalle/ImplicitDifferentiation.jl: Automatic differentiation of implicit functions](https://github.com/gdalle/ImplicitDifferentiation.jl)
  - [gdalle.github.io/ImplicitDifferentiation-JuliaCon2022/](https://gdalle.github.io/ImplicitDifferentiation-JuliaCon2022/)
"""

# ╔═╡ 768c1823-5659-40ca-9f38-afa2cdeea85a
md"""
## Software
"""

# ╔═╡ 2878a88c-f60f-47dd-8814-dd17ea172ea6
md"""

- [Open energy system models - Wikipedia](https://en.wikipedia.org/wiki/Open_energy_system_models#AnyMOD.jl)
- [Open Models - wiki.openmod-initiative.org](https://wiki.openmod-initiative.org/wiki/Open_Models)
- [Energy Models](https://energymodels.de/)


- [GAMS-dev/gams.jl: A MathOptInterface Optimizer to solve JuMP models using GAMS](https://github.com/GAMS-dev/gams.jl)
- [Breakthrough-Energy/REISE.jl: Renewable Energy Integration Simulation Engine](https://github.com/Breakthrough-Energy/REISE.jl)
  - [Facilitating the Energy Transition — documentation](https://breakthrough-energy.github.io/docs/)
- [YoungFaithful/CapacityExpansion.jl: Capacity Expansion Problem Formulation for Julia](https://github.com/YoungFaithful/CapacityExpansion.jl/tree/master)
  - [Homework: Modeling Exercise · CapacityExpansion.jl](https://youngfaithful.github.io/CapacityExpansion.jl/stable/homework/)
- [leonardgoeke/AnyMOD.jl: Julia framework for energy system models with a focus on multi-period capacity expansion](https://github.com/leonardgoeke/AnyMOD.jl)
  - [Open source tool AnyMOD.jl for energy system modelling released! - Osmose](https://www.osmose-h2020.eu/open-source-tool-anymod-jl-for-energy-system-modelling-released/)
  - [[2011.00895] AnyMOD.jl: A Julia package for creating energy system models](https://arxiv.org/abs/2011.00895)
  - [AnyMOD.jl: A Julia package for creating energy system models :: JuliaCon 2021 (times are UTC) :: pretalx](https://pretalx.com/juliacon2021/talk/EUVCJY/)
- [(1523) Power Market Tool (POMATO) | Richard Weinhold | JuliaCon2021 - YouTube](https://www.youtube.com/watch?v=n0wmYTm6Y64)
- [Stephan Buchert / Sun position · GitLab](https://gitlab.com/stephancb/sun-position)
  - [Introduction · PowerModelsONM](https://lanl-ansi.github.io/PowerModelsONM.jl/stable/)
  - [Beginners Guide · PowerModelsONM](https://lanl-ansi.github.io/PowerModelsONM.jl/stable/tutorials/Beginners%20Guide.html#Installing-and-running-Pluto.jl)

\
PV:

- [CliMA/Insolation.jl](https://github.com/CliMA/Insolation.jl)
  - [Home · Insolation.jl](https://clima.github.io/Insolation.jl/dev/)


[Stephan Buchert / Sun position · GitLab](https://gitlab.com/stephancb/sun-position)

[Drawing the analemma with Julia](https://giordano.github.io/blog/2017-11-12-analemma/)




"""

# ╔═╡ 20c7819f-6d17-45b5-b317-b91ed5dc7715


# ╔═╡ 14256fdb-3da3-41b9-ad4f-17a51df2934c


# ╔═╡ 985d7745-19b2-4e39-84eb-9b12982d42a4


# ╔═╡ 0ccaefcd-fa8c-40c5-9dea-0600d4901add


# ╔═╡ 7f94c1eb-b316-4726-a84a-7c7b0e814b29
md"""
## Data
"""

# ╔═╡ 8011d698-a78a-4371-bc57-49acc2bdd3b2
md"""
[JRC Photovoltaic Geographical Information System (PVGIS) - European Commission](https://re.jrc.ec.europa.eu/pvg_tools/en/)
- [PVGIS user manual](https://joint-research-centre.ec.europa.eu/pvgis-online-tool/getting-started-pvgis/pvgis-user-manual_en#ref-9-hourly-solar-radiation-and-pv-data)

\
Load, wind and solar, prices in hourly resolution:
- [Data Platform – Open Power System Data](https://data.open-power-system-data.org/time_series/2020-10-06)

\
[Global Solar Atlas, Portugal](https://globalsolaratlas.info/download/portugal)

[Data and Tools | Photovoltaic Research | NREL](https://www.nrel.gov/pv/data-tools.html)


"""

# ╔═╡ 86af3f0d-5ca1-408c-9a17-e041d415ca21


# ╔═╡ b278cb84-febd-4e95-9f02-e2febc08e477


# ╔═╡ 494c685d-d18e-43fb-adcc-8b8907fcf229


# ╔═╡ 166429fb-6148-414d-b717-2a32c610c321
md"""
# Tests
"""

# ╔═╡ cd353619-814e-4114-a0eb-ad77896b418a
md"""
end-use sectors: residential, commercial, industrial, transportation
"""

# ╔═╡ d5463e21-2f9d-4469-b51e-e349e4949f30
12+16+36+30

# ╔═╡ f0d2d1e1-279d-4fa7-9005-8d404724663c
#begin
	#src = [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,]
	#dst = [5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8, 11, 5, 6, 7, 8, 9, 10, 11, 12]
	#weights = [10, 3, 0.1, 6, 20, 2, 0.1, 8, 11, 10, 4, 1, 30, 40, 0.3, 0.2, 0.5, 13, 17, 38, 30]
	
#end;

# ╔═╡ 47abef49-02ae-4bbf-9986-42629d25695f
#begin
	#src = [1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 4, 5]
	#dst = [5, 6, 7, 8, 9, 3, 7, 4, 7, 8, 8, 8]
	#weights = [20, 3, 1, 0.2, 0.4, 2.8, 1, 0.45, 4.5, 3.3, 1, 2]
	
#end;

# ╔═╡ de3ddaaa-5ffb-4c24-959e-bcd60ca9d548
nameH2 = [
    "Solar PV", "Wind", "Biomass", "Other RES",
    "Power-to-Power", "Power-to-Gas", "Power-to-Liquid", "Power-to-Solid",
    "Residential", "Commercial", "Industrial", "Transportation", "Electricity"
]

# ╔═╡ 9a00ece9-ddab-4206-9154-c0420d2bb801
0.3+0.8+3.0+0.6

# ╔═╡ 684f263a-78ef-4251-b589-089192e9ed9b
begin
#1: PV=20: ESS=5 (P,S,L,G=4,0.1,0.3,0.6 ); E=15: I,T,C,R=6,4,3,2
#2: Wind=30: ESS=8 (P,S,L,G=6,0.2,0.8,1 ); E=22: I,T,C,R=8,6,5,3
#3: bioM=60: ESS=16 (P,S,L,G=1,2,3,10);  E=14: I,T,C,R=bio_30+4,8,1,1
#4: oRES=50: ESS=13 (P,S,L,G=10,0.2,0.6,1.2); E=37: I,T,C,R=14,10,8,5
#5: P2P=21: I,T,C,R=9,7,3,2
#8: P2S=2.5: I,T,C,R=1.2,0.8,0.3,0.2
#7: P2L=4.7: I,T,C,R=0.7,4,-,-
#6: P2G=12.8: I,T,C,R=12.8,-,-,-
#13: E=88: I,T,C,R=32,28,17,11
	src = [1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,13,13,13,13,5,5,5,5,8,8,8,8,7,7,6]
	dst = [13,5,8,7,6,13,5,7,7,6,11,13,5,8,7,6,13,5,8,7,6,11,12,10,9,11,12,10,9,11,12,10,9,11,12,11]
	weights = [15,4,0.1,0.3,0.6,22,6,0.2,0.8,1,30,14,1,2,3,10,37,10,0.2,0.6,1.2,32,28,17,11,9,7,3,2,1.2,0.8,0.3,0.2,0.7,4,12.8]
	size.([src, dst, weights])
end

# ╔═╡ d998e69b-852c-4a02-ae4f-2f4444fafbfd
md"""
ver por causa do power-to-heat: [What is Power-to-X?](https://www.turbomachinerymag.com/view/what-is-power-to-x)
"""

# ╔═╡ e030dc46-e87a-4429-8a61-3a51122b02b3
#sankey(src, dst, weights; max_plot_size = 800)

# ╔═╡ 021628d0-a170-4e9c-8079-f50722bb03b9
energy_colors = palette(:seaborn_colorblind)[[9,10,6,3]]

# ╔═╡ bdfbb0ea-1f67-44fa-b74d-051c2aadee31
#sankey(src, dst, weights; max_plot_size = 800)
sankey(src, dst, weights; node_labels=nameH2, label_position=:bottom, edge_color=:gradient, compact=:true, node_colors=energy_colors,)

# ╔═╡ 85a0eb7e-3f79-46ee-a6fe-935e7ab7f331
palette(:seaborn_colorblind)

# ╔═╡ adbe0aea-37b2-4208-8a49-829408a286f2
names = [
    "PV",
    "Electricity Buy",
    "Battery storage",
    "Heat pump",
    "Biomass",
    "Electricity Sell",
    "Electricity Demand",
    "Heat demand", "9"
]

# ╔═╡ cf23420f-30e9-432f-8ef9-3fbd6498594d
# ╠═╡ disabled = true
#=╠═╡
sankey(src, dst, weights; node_labels=names, node_colors=energy_colors,
    edge_color=:gradient, label_position=:bottom, label_size=7,
    compact=true,
    #force_layer=[6=>2],
    #force_order=[5=>1],
	#figsize=(7, 7)
)
  ╠═╡ =#

# ╔═╡ 2776bc41-7d1d-4876-b281-e93ccba93733


# ╔═╡ e42d7c0c-559e-4507-be56-c87414749d19
t = Date(2023, 4, 27)

# ╔═╡ 0c69c9d1-4182-4e69-a1cc-14edd386ec24
ty = Dates.dayofyear(t)

# ╔═╡ 01d9a20d-5b08-47ff-b96d-3e8582d2cff5


# ╔═╡ e969a627-d5bd-4595-a92c-2b855a2afd02


# ╔═╡ d1a72462-9716-420a-ba54-dddb1c2fc562
md"""
# Notas (reunião TFM com Derik e Prof. P.Fonte):

## 17-Abril-2023:
-  utilizar vídeo para gravar os dados do PC... + go-pro para eletrolisador?
"""

# ╔═╡ 4cb19857-6643-4236-82f5-6f612e57c393


# ╔═╡ 5bc5e16f-36d1-4c78-a493-ac3013eb2891
md"""
# TODO
"""

# ╔═╡ 7ec19209-4590-466f-90f9-bf5a1b96e94e
md"""

 $(@bind thing1 CheckBox()) review this tool: [^H2RES2], MATLAB\Simulink \
 $(@bind thing2 CheckBox()) ... \

"""

# ╔═╡ b598e525-81a5-4451-a891-6e3cea23762f


# ╔═╡ 5bbee908-beec-41c8-b4c4-c584a3791cd6
md"""
# References
"""

# ╔═╡ ecb76401-1476-4d64-829d-9c211fbbabdb
md"""
[^Sevjidsuren2012]: 
$(DOI("10.5772/50602")) 

\

[^H2RES2]: 
$(DOI("10.1016/j.ijhydene.2017.02.139"))
"""

# ╔═╡ 8f253d91-337f-4b8e-8664-bc76af44ed40


# ╔═╡ deb0ddc7-3e9f-44e7-9d23-cd1f2125c960
md"""
## Read later
"""

# ╔═╡ 3d1e656a-502b-43d9-a0e5-ebae49794e34
md"""
- [Breakthrough in hydrogen fuel production could revolutionize alternative energy market | VTx | Virginia Tech](https://vtx.vt.edu/articles/2013/04/040413-cals-hydrogen.html)[Breakthrough in hydrogen fuel production could revolutionize alternative energy market | VTx | Virginia Tech](https://vtx.vt.edu/articles/2013/04/040413-cals-hydrogen.html)


- [Hydrogen for ground transportation and heating is a bad idea | ETH Zurich](https://ethz.ch/en/news-and-events/eth-news/news/2021/11/hydrogen-for-ground-transportation-and-heating-is-a-bad-idea.html)


- [Hydrogen for light road transport: It's got a long way to go on costs](https://thedriven.io/2019/03/27/hydrogen-for-light-road-its-got-a-long-way-to-go-on-costs/)


- [The ANZ Hydrogen Handbook - AH2 anz.com](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.anz.com%2Fcontent%2Fdam%2Fanzcom%2Fpdf%2Finstitutional%2Freports%2Fhydrogen-handbook.pdf&psig=AOvVaw1JEr6R4nilFzYX2jBa1zct&ust=1668076001177000&source=images&cd=vfe&ved=0CHoQr4kDahcKEwiYjJa98aD7AhUAAAAAHQAAAAAQCQ)


- [Why EV Fans should Rethink Hydrogen Cars | by Erik Engheim | Medium](https://erik-engheim.medium.com/why-ev-fans-should-rethink-hydrogen-cars-6d5781a24a14)


- [Why We Need Green Hydrogen](https://news.climate.columbia.edu/2021/01/07/need-green-hydrogen/)


- [The Northeast is poised to become a ‘hydrogen hub’ | Grist](https://grist.org/energy/the-northeast-is-poised-to-become-a-hydrogen-hub/)


"""

# ╔═╡ ddeaf1bf-afae-4663-b69e-da5634c54c2b


# ╔═╡ 1835dbf4-7c67-456e-b994-a2426184d08f
md"""
# Notebook
"""

# ╔═╡ 6e8389d6-8f04-443e-bcc8-0bebc6a96ee9
TableOfContents()

# ╔═╡ 1f38147d-6723-4aa1-81b6-d55b3533c63a
html"""
	<style>
	@media screen {
		main {
			margin: 0 auto;
			max-width: 2000px;
    		padding-left: max(50px, 5%);
    		padding-right: max(283px, 26%); 
            # 383px to accomodate TableOfContents(aside=true)
		}
	}
	</style>

"""

# ╔═╡ 7652d0e6-2c8a-4fc6-89e2-0d8efe4d127d
function green(s::String)
	HTML("<span style='color: hsl(148deg, 63%, 31%);'> $(s)  </span>")
end;

# ╔═╡ 8ce86785-261e-4c5d-a81b-27c2e519a8f6
md"""
Load test on fuel cell Ballard 1200W (46A, 26Vdc).

In the paper [^Sevjidsuren2012] an energy analysis of the same Fuel Cell is reported.

**$(green("Lab test date: 20/DEC/2022"))**
"""

# ╔═╡ a8bba66f-719f-4254-bca0-64f41ea15e23
md"""
**$(green("Lab setup date: 17/APR/2023"))**
"""

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
SankeyPlots = "8fd88ec8-d95c-41fc-b299-05f2225f2cc5"
ShortCodes = "f62ebe17-55c5-4640-972f-b59c0dd11ccf"

[compat]
JuMP = "~1.10.0"
Plots = "~1.38.0"
PlutoTeachingTools = "~0.2.5"
PlutoUI = "~0.7.48"
SankeyPlots = "~0.2.2"
ShortCodes = "~0.3.3"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.3"
manifest_format = "2.0"
project_hash = "d3e6bb1b238e379504a5b99a7baba431c33c5f5e"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "8eaf9f1b4921132a4cff3f36a1d9ba923b14a481"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.1.4"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.1"

[[deps.ArnoldiMethod]]
deps = ["LinearAlgebra", "Random", "StaticArrays"]
git-tree-sha1 = "62e51b39331de8911e4a7ff6f5aaf38a5f4cc0ae"
uuid = "ec485272-7323-5ecc-a04f-4719b315124d"
version = "0.2.0"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.BenchmarkTools]]
deps = ["JSON", "Logging", "Printf", "Profile", "Statistics", "UUIDs"]
git-tree-sha1 = "d9a9701b899b30332bbcb3e1679c41cce81fb0e8"
uuid = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
version = "1.3.2"

[[deps.BitFlags]]
git-tree-sha1 = "43b1a4a8f797c1cddadf60499a8a077d4af2cd2d"
uuid = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
version = "0.1.7"

[[deps.Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "19a35467a82e236ff51bc17a3a44b69ef35185a2"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.8+0"

[[deps.CEnum]]
git-tree-sha1 = "eb4cb44a499229b3b8426dcfb5dd85333951ff90"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.2"

[[deps.Cairo_jll]]
deps = ["Artifacts", "Bzip2_jll", "CompilerSupportLibraries_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "JLLWrappers", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "4b859a208b2397a7a623a03449e4636bdb17bcf2"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.1+1"

[[deps.CodeTracking]]
deps = ["InteractiveUtils", "UUIDs"]
git-tree-sha1 = "d730914ef30a06732bdd9f763f6cc32e92ffbff1"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "1.3.1"

[[deps.CodecBzip2]]
deps = ["Bzip2_jll", "Libdl", "TranscodingStreams"]
git-tree-sha1 = "2e62a725210ce3c3c2e1a3080190e7ca491f18d7"
uuid = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
version = "0.7.2"

[[deps.CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "9c209fb7536406834aa938fb149964b985de6c83"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.1"

[[deps.ColorSchemes]]
deps = ["ColorTypes", "ColorVectorSpace", "Colors", "FixedPointNumbers", "PrecompileTools", "Random"]
git-tree-sha1 = "be6ab11021cd29f0344d5c4357b163af05a48cba"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.21.0"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "eb7f0f8307f71fac7c606984ea5fb2817275d6e4"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.11.4"

[[deps.ColorVectorSpace]]
deps = ["ColorTypes", "FixedPointNumbers", "LinearAlgebra", "SpecialFunctions", "Statistics", "TensorCore"]
git-tree-sha1 = "600cc5508d66b78aae350f7accdb58763ac18589"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.9.10"

[[deps.Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "fc08e5930ee9a4e03f84bfb5211cb54e7769758a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.10"

[[deps.CommonSubexpressions]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "7b8a93dba8af7e3b42fecabf646260105ac373f7"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.3.0"

[[deps.Compat]]
deps = ["UUIDs"]
git-tree-sha1 = "7a60c856b9fa189eb34f5f8a6f6b5529b7942957"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "4.6.1"
weakdeps = ["Dates", "LinearAlgebra"]

    [deps.Compat.extensions]
    CompatLinearAlgebraExt = "LinearAlgebra"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "1.0.5+0"

[[deps.ConcurrentUtilities]]
deps = ["Serialization", "Sockets"]
git-tree-sha1 = "96d823b94ba8d187a6d8f0826e731195a74b90e9"
uuid = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
version = "2.2.0"

[[deps.Contour]]
git-tree-sha1 = "d05d9e7b7aedff4e5b51a029dced05cfb6125781"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.6.2"

[[deps.DataAPI]]
git-tree-sha1 = "e8119c1a33d267e16108be441a287a6981ba1630"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.14.0"

[[deps.DataStructures]]
deps = ["Compat", "InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "d1fff3a548102f48987a52a2e0d114fa97d730f0"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.18.13"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
git-tree-sha1 = "9e2f36d3c96a820c678f2f1f1782582fcf685bae"
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"
version = "1.9.1"

[[deps.DiffResults]]
deps = ["StaticArraysCore"]
git-tree-sha1 = "782dd5f4561f5d267313f23853baaaa4c52ea621"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "1.1.0"

[[deps.DiffRules]]
deps = ["IrrationalConstants", "LogExpFunctions", "NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "a4ad7ef19d2cdc2eff57abbbe68032b1cd0bd8f8"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.13.0"

[[deps.Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[deps.DocStringExtensions]]
deps = ["LibGit2"]
git-tree-sha1 = "2fb1e02f2b635d0845df5d7c167fec4dd739b00d"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.9.3"

[[deps.Downloads]]
deps = ["ArgTools", "FileWatching", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
version = "1.6.0"

[[deps.ECOS]]
deps = ["CEnum", "ECOS_jll", "MathOptInterface"]
git-tree-sha1 = "d1c761af75addf7a29dbb95e488efe57cd9140bd"
uuid = "e2685f51-7e38-5353-a97d-a921fd2c8199"
version = "1.1.1"

[[deps.ECOS_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "5f84034ddd642cf595e57d46ea2f085321c260e4"
uuid = "c2c64177-6a8e-5dca-99a7-64895ad7445f"
version = "200.0.800+0"

[[deps.EpollShim_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "8e9441ee83492030ace98f9789a654a6d0b1f643"
uuid = "2702e6a9-849d-5ed8-8c21-79e8b8f9ee43"
version = "0.0.20230411+0"

[[deps.Expat_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "bad72f730e9e91c08d9427d5e8db95478a3c323d"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.4.8+0"

[[deps.FFMPEG]]
deps = ["FFMPEG_jll"]
git-tree-sha1 = "b57e3acbe22f8484b4b5ff66a7499717fe1a9cc8"
uuid = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
version = "0.4.1"

[[deps.FFMPEG_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "JLLWrappers", "LAME_jll", "Libdl", "Ogg_jll", "OpenSSL_jll", "Opus_jll", "PCRE2_jll", "Pkg", "Zlib_jll", "libaom_jll", "libass_jll", "libfdk_aac_jll", "libvorbis_jll", "x264_jll", "x265_jll"]
git-tree-sha1 = "74faea50c1d007c85837327f6775bea60b5492dd"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
version = "4.4.2+2"

[[deps.FileIO]]
deps = ["Pkg", "Requires", "UUIDs"]
git-tree-sha1 = "299dc33549f68299137e51e6d49a13b5b1da9673"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.16.1"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[deps.Fontconfig_jll]]
deps = ["Artifacts", "Bzip2_jll", "Expat_jll", "FreeType2_jll", "JLLWrappers", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "21efd19106a55620a188615da6d3d06cd7f6ee03"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.93+0"

[[deps.Formatting]]
deps = ["Printf"]
git-tree-sha1 = "8339d61043228fdd3eb658d86c926cb282ae72a8"
uuid = "59287772-0a20-5a39-b81b-1366585eb4c0"
version = "0.4.2"

[[deps.ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "LinearAlgebra", "LogExpFunctions", "NaNMath", "Preferences", "Printf", "Random", "SpecialFunctions"]
git-tree-sha1 = "00e252f4d706b3d55a8863432e742bf5717b498d"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.10.35"
weakdeps = ["StaticArrays"]

    [deps.ForwardDiff.extensions]
    ForwardDiffStaticArraysExt = "StaticArrays"

[[deps.FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.4+0"

[[deps.FriBidi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.10+0"

[[deps.GLFW_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libglvnd_jll", "Pkg", "Xorg_libXcursor_jll", "Xorg_libXi_jll", "Xorg_libXinerama_jll", "Xorg_libXrandr_jll"]
git-tree-sha1 = "d972031d28c8c8d9d7b41a536ad7bb0c2579caca"
uuid = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
version = "3.3.8+0"

[[deps.GR]]
deps = ["Artifacts", "Base64", "DelimitedFiles", "Downloads", "GR_jll", "HTTP", "JSON", "Libdl", "LinearAlgebra", "Pkg", "Preferences", "Printf", "Random", "Serialization", "Sockets", "TOML", "Tar", "Test", "UUIDs", "p7zip_jll"]
git-tree-sha1 = "efaac003187ccc71ace6c755b197284cd4811bfe"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.72.4"

[[deps.GR_jll]]
deps = ["Artifacts", "Bzip2_jll", "Cairo_jll", "FFMPEG_jll", "Fontconfig_jll", "GLFW_jll", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pixman_jll", "Qt5Base_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "4486ff47de4c18cb511a0da420efebb314556316"
uuid = "d2c73de3-f751-5644-a686-071e5b155ba9"
version = "0.72.4+0"

[[deps.Gettext_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.21.0+0"

[[deps.Glib_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE2_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "d3b3624125c1474292d0d8ed0f65554ac37ddb23"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.74.0+2"

[[deps.Graphite2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "344bf40dcab1073aca04aa0df4fb092f920e4011"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.14+0"

[[deps.Graphs]]
deps = ["ArnoldiMethod", "Compat", "DataStructures", "Distributed", "Inflate", "LinearAlgebra", "Random", "SharedArrays", "SimpleTraits", "SparseArrays", "Statistics"]
git-tree-sha1 = "1cf1d7dcb4bc32d7b4a5add4232db3750c27ecb4"
uuid = "86223c79-3864-5bf0-83f7-82e725a168b6"
version = "1.8.0"

[[deps.Grisu]]
git-tree-sha1 = "53bb909d1151e57e2484c3d1b53e19552b887fb2"
uuid = "42e2da0e-8278-4e71-bc24-59509adca0fe"
version = "1.0.2"

[[deps.HTTP]]
deps = ["Base64", "CodecZlib", "ConcurrentUtilities", "Dates", "Logging", "LoggingExtras", "MbedTLS", "NetworkOptions", "OpenSSL", "Random", "SimpleBufferStream", "Sockets", "URIs", "UUIDs"]
git-tree-sha1 = "42c6b37c6a2242cb646a1dd5518631db0be9b967"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "1.8.1"

[[deps.HarfBuzz_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "129acf094d168394e80ee1dc4bc06ec835e510a3"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.8.1+1"

[[deps.HiGHS]]
deps = ["HiGHS_jll", "MathOptInterface", "SnoopPrecompile", "SparseArrays"]
git-tree-sha1 = "08535862ef6d42a01ffcaaf6507cfb8a0fe329a6"
uuid = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
version = "1.5.1"

[[deps.HiGHS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "53aadc2a53ef3ecc4704549b4791dea67657a4bb"
uuid = "8fd58aa0-07eb-5a78-9b36-339c94fd15ea"
version = "1.5.1+0"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "8d511d5b81240fc8e6802386302675bdf47737b9"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.4"

[[deps.HypertextLiteral]]
deps = ["Tricks"]
git-tree-sha1 = "c47c5fa4c5308f27ccaac35504858d8914e102f9"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.4"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "f7be53659ab06ddc986428d3a9dcc95f6fa6705a"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.2"

[[deps.Inflate]]
git-tree-sha1 = "5cd07aab533df5170988219191dfad0519391428"
uuid = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
version = "0.1.3"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.IrrationalConstants]]
git-tree-sha1 = "630b497eafcc20001bba38a4651b327dcfc491d2"
uuid = "92d709cd-6900-40b7-9082-c6be49f344b6"
version = "0.2.2"

[[deps.IterTools]]
git-tree-sha1 = "fa6287a4469f5e048d763df38279ee729fbd44e5"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.4.0"

[[deps.JLD2]]
deps = ["FileIO", "MacroTools", "Mmap", "OrderedCollections", "Pkg", "Printf", "Reexport", "Requires", "TranscodingStreams", "UUIDs"]
git-tree-sha1 = "42c17b18ced77ff0be65957a591d34f4ed57c631"
uuid = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
version = "0.4.31"

[[deps.JLFzf]]
deps = ["Pipe", "REPL", "Random", "fzf_jll"]
git-tree-sha1 = "f377670cda23b6b7c1c0b3893e37451c5c1a2185"
uuid = "1019f520-868f-41f5-a6de-eb00f4b6a39c"
version = "0.1.5"

[[deps.JLLWrappers]]
deps = ["Preferences"]
git-tree-sha1 = "abc9885a7ca2052a736a600f7fa66209f96506e1"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.4.1"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "31e996f0a15c7b280ba9f76636b3ff9e2ae58c9a"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.4"

[[deps.JSON3]]
deps = ["Dates", "Mmap", "Parsers", "SnoopPrecompile", "StructTypes", "UUIDs"]
git-tree-sha1 = "84b10656a41ef564c39d2d477d7236966d2b5683"
uuid = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
version = "1.12.0"

[[deps.JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "6f2675ef130a300a112286de91973805fcc5ffbc"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.1.91+0"

[[deps.JuMP]]
deps = ["LinearAlgebra", "MathOptInterface", "MutableArithmetics", "OrderedCollections", "Printf", "SnoopPrecompile", "SparseArrays"]
git-tree-sha1 = "4ec0e68fecbbe1b78db2ddf1ac573963ed5adebc"
uuid = "4076af6c-e467-56ae-b986-b466b2749572"
version = "1.10.0"

[[deps.JuliaInterpreter]]
deps = ["CodeTracking", "InteractiveUtils", "Random", "UUIDs"]
git-tree-sha1 = "6a125e6a4cb391e0b9adbd1afa9e771c2179f8ef"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.9.23"

[[deps.LAME_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "f6250b16881adf048549549fba48b1161acdac8c"
uuid = "c1c5ebd0-6772-5130-a774-d5fcae4a789d"
version = "3.100.1+0"

[[deps.LERC_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "bf36f528eec6634efc60d7ec062008f171071434"
uuid = "88015f11-f218-50d7-93a8-a6af411a945d"
version = "3.0.0+1"

[[deps.LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e5b909bcf985c5e2605737d2ce278ed791b89be6"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.1+0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "f2355693d6778a178ade15952b7ac47a4ff97996"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.0"

[[deps.Latexify]]
deps = ["Formatting", "InteractiveUtils", "LaTeXStrings", "MacroTools", "Markdown", "OrderedCollections", "Printf", "Requires"]
git-tree-sha1 = "8c57307b5d9bb3be1ff2da469063628631d4d51e"
uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
version = "0.15.21"

    [deps.Latexify.extensions]
    DataFramesExt = "DataFrames"
    DiffEqBiologicalExt = "DiffEqBiological"
    ParameterizedFunctionsExt = "DiffEqBase"
    SymEngineExt = "SymEngine"

    [deps.Latexify.weakdeps]
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
    DiffEqBiological = "eb300fae-53e8-50a0-950c-e21f52c2b7e0"
    SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[[deps.LayeredLayouts]]
deps = ["Dates", "ECOS", "Graphs", "HiGHS", "IterTools", "JuMP", "Random"]
git-tree-sha1 = "ee02fc12fc9975133caec989ea811c9ab976de74"
uuid = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
version = "0.2.8"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.6.3"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
version = "7.84.0+0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"
version = "1.10.2+0"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Libffi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0b4a5d71f3e5200a7dff793393e09dfc2d874290"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.2+1"

[[deps.Libgcrypt_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "64613c82a59c120435c067c2b809fc61cf5166ae"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.7+0"

[[deps.Libglvnd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll", "Xorg_libXext_jll"]
git-tree-sha1 = "6f73d1dd803986947b2c750138528a999a6c7733"
uuid = "7e76a0d4-f3c7-5321-8279-8d96eeed0f29"
version = "1.6.0+0"

[[deps.Libgpg_error_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c333716e46366857753e273ce6a69ee0945a6db9"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.42.0+0"

[[deps.Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c7cb1f5d892775ba13767a87c7ada0b980ea0a71"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.1+2"

[[deps.Libmount_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.35.0+0"

[[deps.Libtiff_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "LERC_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "3eb79b0ca5764d4799c06699573fd8f533259713"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.4.0+0"

[[deps.Libuuid_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.36.0+0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "OpenBLAS_jll", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[deps.LogExpFunctions]]
deps = ["DocStringExtensions", "IrrationalConstants", "LinearAlgebra"]
git-tree-sha1 = "0a1b7c2863e44523180fdb3146534e265a91870b"
uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
version = "0.3.23"

    [deps.LogExpFunctions.extensions]
    LogExpFunctionsChainRulesCoreExt = "ChainRulesCore"
    LogExpFunctionsChangesOfVariablesExt = "ChangesOfVariables"
    LogExpFunctionsInverseFunctionsExt = "InverseFunctions"

    [deps.LogExpFunctions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
    InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.LoggingExtras]]
deps = ["Dates", "Logging"]
git-tree-sha1 = "cedb76b37bc5a6c702ade66be44f831fa23c681e"
uuid = "e6f89c97-d47a-5376-807f-9c37f3926c36"
version = "1.0.0"

[[deps.LoweredCodeUtils]]
deps = ["JuliaInterpreter"]
git-tree-sha1 = "60168780555f3e663c536500aa790b6368adc02a"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
version = "2.3.0"

[[deps.MIMEs]]
git-tree-sha1 = "65f28ad4b594aebe22157d6fac869786a255b7eb"
uuid = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
version = "0.1.4"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "42324d08725e200c23d4dfb549e0d5d89dede2d2"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.10"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MathOptInterface]]
deps = ["BenchmarkTools", "CodecBzip2", "CodecZlib", "DataStructures", "ForwardDiff", "JSON", "LinearAlgebra", "MutableArithmetics", "NaNMath", "OrderedCollections", "PrecompileTools", "Printf", "SparseArrays", "SpecialFunctions", "Test", "Unicode"]
git-tree-sha1 = "8e054675d393ce5866dcdd6a071075e25e21a39c"
uuid = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
version = "1.15.1"

[[deps.MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "MozillaCACerts_jll", "Random", "Sockets"]
git-tree-sha1 = "03a9b9718f5682ecb107ac9f7308991db4ce395b"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.1.7"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.28.2+0"

[[deps.Measures]]
git-tree-sha1 = "c13304c81eec1ed3af7fc20e75fb6b26092a1102"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.3.2"

[[deps.Memoize]]
deps = ["MacroTools"]
git-tree-sha1 = "2b1dfcba103de714d31c033b5dacc2e4a12c7caa"
uuid = "c03570c3-d221-55d1-a50c-7939bbd78826"
version = "0.4.4"

[[deps.MetaGraphs]]
deps = ["Graphs", "JLD2", "Random"]
git-tree-sha1 = "1130dbe1d5276cb656f6e1094ce97466ed700e5a"
uuid = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
version = "0.7.2"

[[deps.Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "f66bdc5de519e8f8ae43bdc598782d35a25b1272"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "1.1.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2022.10.11"

[[deps.MutableArithmetics]]
deps = ["LinearAlgebra", "SparseArrays", "Test"]
git-tree-sha1 = "964cb1a7069723727025ae295408747a0b36a854"
uuid = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
version = "1.3.0"

[[deps.NaNMath]]
deps = ["OpenLibm_jll"]
git-tree-sha1 = "0877504529a3e5c3343c6f8b4c0381e57e4387e4"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "1.0.2"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
version = "1.2.0"

[[deps.Ogg_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "887579a3eb005446d514ab7aeac5d1d027658b8f"
uuid = "e7412a2a-1a6e-54c0-be00-318e2571c051"
version = "1.3.5+1"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"
version = "0.3.21+4"

[[deps.OpenLibm_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"
version = "0.8.1+0"

[[deps.OpenSSL]]
deps = ["BitFlags", "Dates", "MozillaCACerts_jll", "OpenSSL_jll", "Sockets"]
git-tree-sha1 = "51901a49222b09e3743c65b8847687ae5fc78eb2"
uuid = "4d8831e6-92b7-49fb-bdf8-b643e874388c"
version = "1.4.1"

[[deps.OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9ff31d101d987eb9d66bd8b176ac7c277beccd09"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.20+0"

[[deps.OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "13652491f6856acfd2db29360e1bbcd4565d04f1"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.5+0"

[[deps.Opus_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "51a08fb14ec28da2ec7a927c4337e4332c2a4720"
uuid = "91d4177d-7536-5919-b921-800302f37372"
version = "1.3.2+0"

[[deps.OrderedCollections]]
git-tree-sha1 = "d321bf2de576bf25ec4d3e4360faca399afca282"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.6.0"

[[deps.PCRE2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"
version = "10.42.0+0"

[[deps.Parsers]]
deps = ["Dates", "SnoopPrecompile"]
git-tree-sha1 = "478ac6c952fddd4399e71d4779797c538d0ff2bf"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.5.8"

[[deps.Pipe]]
git-tree-sha1 = "6842804e7867b115ca9de748a0cf6b364523c16d"
uuid = "b98c9c47-44ae-5843-9183-064241ee97a0"
version = "1.3.0"

[[deps.Pixman_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b4f5d02549a10e20780a24fce72bea96b6329e29"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.40.1+0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "FileWatching", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.9.2"

[[deps.PlotThemes]]
deps = ["PlotUtils", "Statistics"]
git-tree-sha1 = "1f03a2d339f42dca4a4da149c7e15e9b896ad899"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "3.1.0"

[[deps.PlotUtils]]
deps = ["ColorSchemes", "Colors", "Dates", "PrecompileTools", "Printf", "Random", "Reexport", "Statistics"]
git-tree-sha1 = "f92e1315dadf8c46561fb9396e525f7200cdc227"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "1.3.5"

[[deps.Plots]]
deps = ["Base64", "Contour", "Dates", "Downloads", "FFMPEG", "FixedPointNumbers", "GR", "JLFzf", "JSON", "LaTeXStrings", "Latexify", "LinearAlgebra", "Measures", "NaNMath", "Pkg", "PlotThemes", "PlotUtils", "PrecompileTools", "Preferences", "Printf", "REPL", "Random", "RecipesBase", "RecipesPipeline", "Reexport", "RelocatableFolders", "Requires", "Scratch", "Showoff", "SparseArrays", "Statistics", "StatsBase", "UUIDs", "UnicodeFun", "Unzip"]
git-tree-sha1 = "6c7f47fd112001fc95ea1569c2757dffd9e81328"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "1.38.11"

    [deps.Plots.extensions]
    FileIOExt = "FileIO"
    GeometryBasicsExt = "GeometryBasics"
    IJuliaExt = "IJulia"
    ImageInTerminalExt = "ImageInTerminal"
    UnitfulExt = "Unitful"

    [deps.Plots.weakdeps]
    FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
    GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
    IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
    ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
    Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps.PlutoHooks]]
deps = ["InteractiveUtils", "Markdown", "UUIDs"]
git-tree-sha1 = "072cdf20c9b0507fdd977d7d246d90030609674b"
uuid = "0ff47ea0-7a50-410d-8455-4348d5de0774"
version = "0.0.5"

[[deps.PlutoLinks]]
deps = ["FileWatching", "InteractiveUtils", "Markdown", "PlutoHooks", "Revise", "UUIDs"]
git-tree-sha1 = "8f5fa7056e6dcfb23ac5211de38e6c03f6367794"
uuid = "0ff47ea0-7a50-410d-8455-4348d5de0420"
version = "0.1.6"

[[deps.PlutoTeachingTools]]
deps = ["Downloads", "HypertextLiteral", "LaTeXStrings", "Latexify", "Markdown", "PlutoLinks", "PlutoUI", "Random"]
git-tree-sha1 = "88222661708df26242d0bfb9237d023557d11718"
uuid = "661c6b06-c737-4d37-b85c-46df65de6f69"
version = "0.2.11"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "ColorTypes", "Dates", "FixedPointNumbers", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "MIMEs", "Markdown", "Random", "Reexport", "URIs", "UUIDs"]
git-tree-sha1 = "b478a748be27bd2f2c73a7690da219d0844db305"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.51"

[[deps.PrecompileTools]]
deps = ["Preferences"]
git-tree-sha1 = "259e206946c293698122f63e2b513a7c99a244e8"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
version = "1.1.1"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "7eb1686b4f04b82f96ed7a4ea5890a4f0c7a09f1"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.4.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[deps.Qt5Base_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Fontconfig_jll", "Glib_jll", "JLLWrappers", "Libdl", "Libglvnd_jll", "OpenSSL_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libxcb_jll", "Xorg_xcb_util_image_jll", "Xorg_xcb_util_keysyms_jll", "Xorg_xcb_util_renderutil_jll", "Xorg_xcb_util_wm_jll", "Zlib_jll", "xkbcommon_jll"]
git-tree-sha1 = "0c03844e2231e12fda4d0086fd7cbe4098ee8dc5"
uuid = "ea2cea3b-5b76-57ae-a6ef-0a8af62496e1"
version = "5.15.3+2"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.RecipesBase]]
deps = ["PrecompileTools"]
git-tree-sha1 = "5c3d09cc4f31f5fc6af001c250bf1278733100ff"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.3.4"

[[deps.RecipesPipeline]]
deps = ["Dates", "NaNMath", "PlotUtils", "PrecompileTools", "RecipesBase"]
git-tree-sha1 = "45cf9fd0ca5839d06ef333c8201714e888486342"
uuid = "01d81517-befc-4cb6-b9ec-a95719d0359c"
version = "0.6.12"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.RelocatableFolders]]
deps = ["SHA", "Scratch"]
git-tree-sha1 = "90bc7a7c96410424509e4263e277e43250c05691"
uuid = "05181044-ff0b-4ac5-8273-598c1e38db00"
version = "1.0.0"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "838a3a4188e2ded87a4f9f184b4b0d78a1e91cb7"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.3.0"

[[deps.Revise]]
deps = ["CodeTracking", "Distributed", "FileWatching", "JuliaInterpreter", "LibGit2", "LoweredCodeUtils", "OrderedCollections", "Pkg", "REPL", "Requires", "UUIDs", "Unicode"]
git-tree-sha1 = "feafdc70b2e6684314e188d95fe66d116de834a7"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "3.5.2"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.SankeyPlots]]
deps = ["Graphs", "LayeredLayouts", "MetaGraphs", "Plots", "RecipesBase", "SparseArrays"]
git-tree-sha1 = "0281823a940768f3d8828f292ec64a51039e2ccf"
uuid = "8fd88ec8-d95c-41fc-b299-05f2225f2cc5"
version = "0.2.2"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "30449ee12237627992a99d5e30ae63e4d78cd24a"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.2.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[deps.ShortCodes]]
deps = ["Base64", "CodecZlib", "HTTP", "JSON3", "Memoize", "UUIDs"]
git-tree-sha1 = "95479a28f0bb4ad37ec7c7ece7fdbfc400c643e0"
uuid = "f62ebe17-55c5-4640-972f-b59c0dd11ccf"
version = "0.3.5"

[[deps.Showoff]]
deps = ["Dates", "Grisu"]
git-tree-sha1 = "91eddf657aca81df9ae6ceb20b959ae5653ad1de"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "1.0.3"

[[deps.SimpleBufferStream]]
git-tree-sha1 = "874e8867b33a00e784c8a7e4b60afe9e037b74e1"
uuid = "777ac1f9-54b0-4bf8-805c-2214025038e7"
version = "1.1.0"

[[deps.SimpleTraits]]
deps = ["InteractiveUtils", "MacroTools"]
git-tree-sha1 = "5d7e3f4e11935503d3ecaf7186eac40602e7d231"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
version = "0.9.4"

[[deps.SnoopPrecompile]]
deps = ["Preferences"]
git-tree-sha1 = "e760a70afdcd461cf01a575947738d359234665c"
uuid = "66db9d55-30c0-4569-8b51-7e840670fc0c"
version = "1.0.3"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.SortingAlgorithms]]
deps = ["DataStructures"]
git-tree-sha1 = "a4ada03f999bd01b3a25dcaa30b2d929fe537e00"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "1.1.0"

[[deps.SparseArrays]]
deps = ["Libdl", "LinearAlgebra", "Random", "Serialization", "SuiteSparse_jll"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[deps.SpecialFunctions]]
deps = ["IrrationalConstants", "LogExpFunctions", "OpenLibm_jll", "OpenSpecFun_jll"]
git-tree-sha1 = "ef28127915f4229c971eb43f3fc075dd3fe91880"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "2.2.0"

    [deps.SpecialFunctions.extensions]
    SpecialFunctionsChainRulesCoreExt = "ChainRulesCore"

    [deps.SpecialFunctions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[[deps.StaticArrays]]
deps = ["LinearAlgebra", "Random", "StaticArraysCore", "Statistics"]
git-tree-sha1 = "c262c8e978048c2b095be1672c9bee55b4619521"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.5.24"

[[deps.StaticArraysCore]]
git-tree-sha1 = "6b7ba252635a5eff6a0b0664a41ee140a1c9e72a"
uuid = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
version = "1.4.0"

[[deps.Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
version = "1.9.0"

[[deps.StatsAPI]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "45a7769a04a3cf80da1c1c7c60caf932e6f4c9f7"
uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
version = "1.6.0"

[[deps.StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "LogExpFunctions", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "d1bf48bfcc554a3761a133fe3a9bb01488e06916"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.33.21"

[[deps.StructTypes]]
deps = ["Dates", "UUIDs"]
git-tree-sha1 = "ca4bccb03acf9faaf4137a9abc1881ed1841aa70"
uuid = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
version = "1.10.0"

[[deps.SuiteSparse_jll]]
deps = ["Artifacts", "Libdl", "Pkg", "libblastrampoline_jll"]
uuid = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
version = "5.10.1+6"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
version = "1.10.0"

[[deps.TensorCore]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "1feb45f88d133a655e001435632f019a9a1bcdb6"
uuid = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50"
version = "0.1.1"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "9a6ae7ed916312b41236fcef7e0af564ef934769"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.13"

[[deps.Tricks]]
git-tree-sha1 = "aadb748be58b492045b4f56166b5188aa63ce549"
uuid = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
version = "0.1.7"

[[deps.URIs]]
git-tree-sha1 = "074f993b0ca030848b897beff716d93aca60f06a"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.4.2"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.UnicodeFun]]
deps = ["REPL"]
git-tree-sha1 = "53915e50200959667e78a92a418594b428dffddf"
uuid = "1cfade01-22cf-5700-b092-accc4b62d6e1"
version = "0.4.1"

[[deps.Unzip]]
git-tree-sha1 = "ca0969166a028236229f63514992fc073799bb78"
uuid = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
version = "0.2.0"

[[deps.Wayland_jll]]
deps = ["Artifacts", "EpollShim_jll", "Expat_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "ed8d92d9774b077c53e1da50fd81a36af3744c1c"
uuid = "a2964d1f-97da-50d4-b82a-358c7fce9d89"
version = "1.21.0+0"

[[deps.Wayland_protocols_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4528479aa01ee1b3b4cd0e6faef0e04cf16466da"
uuid = "2381bf8a-dfd0-557d-9999-79630e7b1b91"
version = "1.25.0+0"

[[deps.XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "93c41695bc1c08c46c5899f4fe06d6ead504bb73"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.10.3+0"

[[deps.XSLT_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgcrypt_jll", "Libgpg_error_jll", "Libiconv_jll", "Pkg", "XML2_jll", "Zlib_jll"]
git-tree-sha1 = "91844873c4085240b95e795f692c4cec4d805f8a"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.34+0"

[[deps.Xorg_libX11_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "5be649d550f3f4b95308bf0183b82e2582876527"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+4"

[[deps.Xorg_libXau_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4e490d5c960c314f33885790ed410ff3a94ce67e"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+4"

[[deps.Xorg_libXcursor_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXfixes_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "12e0eb3bc634fa2080c1c37fccf56f7c22989afd"
uuid = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
version = "1.2.0+4"

[[deps.Xorg_libXdmcp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fe47bd2247248125c428978740e18a681372dd4"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+4"

[[deps.Xorg_libXext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "b7c0aa8c376b31e4852b360222848637f481f8c3"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+4"

[[deps.Xorg_libXfixes_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "0e0dc7431e7a0587559f9294aeec269471c991a4"
uuid = "d091e8ba-531a-589c-9de9-94069b037ed8"
version = "5.0.3+4"

[[deps.Xorg_libXi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXfixes_jll"]
git-tree-sha1 = "89b52bc2160aadc84d707093930ef0bffa641246"
uuid = "a51aa0fd-4e3c-5386-b890-e753decda492"
version = "1.7.10+4"

[[deps.Xorg_libXinerama_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll"]
git-tree-sha1 = "26be8b1c342929259317d8b9f7b53bf2bb73b123"
uuid = "d1454406-59df-5ea1-beac-c340f2130bc3"
version = "1.1.4+4"

[[deps.Xorg_libXrandr_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll"]
git-tree-sha1 = "34cea83cb726fb58f325887bf0612c6b3fb17631"
uuid = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
version = "1.5.2+4"

[[deps.Xorg_libXrender_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "19560f30fd49f4d4efbe7002a1037f8c43d43b96"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+4"

[[deps.Xorg_libpthread_stubs_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+3"

[[deps.Xorg_libxcb_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "daf17f441228e7a3833846cd048892861cff16d6"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+3"

[[deps.Xorg_libxkbfile_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "926af861744212db0eb001d9e40b5d16292080b2"
uuid = "cc61e674-0454-545c-8b26-ed2c68acab7a"
version = "1.1.0+4"

[[deps.Xorg_xcb_util_image_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "0fab0a40349ba1cba2c1da699243396ff8e94b97"
uuid = "12413925-8142-5f55-bb0e-6d7ca50bb09b"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll"]
git-tree-sha1 = "e7fd7b2881fa2eaa72717420894d3938177862d1"
uuid = "2def613f-5ad1-5310-b15b-b15d46f528f5"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_keysyms_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "d1151e2c45a544f32441a567d1690e701ec89b00"
uuid = "975044d2-76e6-5fbe-bf08-97ce7c6574c7"
version = "0.4.0+1"

[[deps.Xorg_xcb_util_renderutil_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "dfd7a8f38d4613b6a575253b3174dd991ca6183e"
uuid = "0d47668e-0667-5a69-a72c-f761630bfb7e"
version = "0.3.9+1"

[[deps.Xorg_xcb_util_wm_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xcb_util_jll"]
git-tree-sha1 = "e78d10aab01a4a154142c5006ed44fd9e8e31b67"
uuid = "c22f9ab0-d5fe-5066-847c-f4bb1cd4e361"
version = "0.4.1+1"

[[deps.Xorg_xkbcomp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxkbfile_jll"]
git-tree-sha1 = "4bcbf660f6c2e714f87e960a171b119d06ee163b"
uuid = "35661453-b289-5fab-8a00-3d9160c6a3a4"
version = "1.4.2+4"

[[deps.Xorg_xkeyboard_config_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_xkbcomp_jll"]
git-tree-sha1 = "5c8424f8a67c3f2209646d4425f3d415fee5931d"
uuid = "33bec58e-1273-512f-9401-5d533626f822"
version = "2.27.0+4"

[[deps.Xorg_xtrans_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79c31e7844f6ecf779705fbc12146eb190b7d845"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+3"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.13+0"

[[deps.Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "49ce682769cd5de6c72dcf1b94ed7790cd08974c"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.5.5+0"

[[deps.fzf_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "868e669ccb12ba16eaf50cb2957ee2ff61261c56"
uuid = "214eeab7-80f7-51ab-84ad-2988db7cef09"
version = "0.29.0+0"

[[deps.libaom_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "3a2ea60308f0996d26f1e5354e10c24e9ef905d4"
uuid = "a4ae2306-e953-59d6-aa16-d00cac43593b"
version = "3.4.0+0"

[[deps.libass_jll]]
deps = ["Artifacts", "Bzip2_jll", "FreeType2_jll", "FriBidi_jll", "HarfBuzz_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "5982a94fcba20f02f42ace44b9894ee2b140fe47"
uuid = "0ac62f75-1d6f-5e53-bd7c-93b484bb37c0"
version = "0.15.1+0"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"
version = "5.8.0+0"

[[deps.libfdk_aac_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "daacc84a041563f965be61859a36e17c4e4fcd55"
uuid = "f638f0a6-7fb0-5443-88ba-1cc74229b280"
version = "2.0.2+0"

[[deps.libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.38+0"

[[deps.libvorbis_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ogg_jll", "Pkg"]
git-tree-sha1 = "b910cb81ef3fe6e78bf6acee440bda86fd6ae00c"
uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
version = "1.3.7+1"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"
version = "1.48.0+0"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
version = "17.4.0+0"

[[deps.x264_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fea590b89e6ec504593146bf8b988b2c00922b2"
uuid = "1270edf5-f2f9-52d2-97e9-ab00b5d0237a"
version = "2021.5.5+0"

[[deps.x265_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "ee567a171cce03570d77ad3a43e90218e38937a9"
uuid = "dfaa095f-4041-5dcd-9319-2fabd8486b76"
version = "3.5.0+0"

[[deps.xkbcommon_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Wayland_jll", "Wayland_protocols_jll", "Xorg_libxcb_jll", "Xorg_xkeyboard_config_jll"]
git-tree-sha1 = "9ebfc140cc56e8c2156a15ceac2f0302e327ac0a"
uuid = "d8fb68d0-12a3-5cfd-a85a-d49703b185fd"
version = "1.4.1+0"
"""

# ╔═╡ Cell order:
# ╟─f09d1eda-bfcb-4ab9-b1ce-2f59fd9747c9
# ╟─60119a67-1aa0-4c7e-8514-45420e576d83
# ╟─c3968558-28ee-49f1-9e87-d2d88f166abb
# ╟─394b7f89-7259-4339-b6c9-df9e82fba253
# ╟─6a4a8025-9184-4e93-a80e-eddea4857658
# ╠═c5c096c9-36d2-49f3-9ce1-853eabf1aaf0
# ╟─2ba7396c-20f4-4995-a609-7794e34c1648
# ╟─0323250e-3146-45ce-a87c-d8e53fa25938
# ╟─7d086988-14ac-47fb-87dd-ed0235fa13d3
# ╠═e7002bff-26cc-4f1d-80cb-89da0adcb7dd
# ╠═0d054678-b051-4abe-a77d-6af8978edb28
# ╠═bf816930-4a28-11ed-18ae-ff9176a0e53f
# ╟─442f8172-c833-42e8-9f58-d4674a2fb070
# ╟─1ef6b34b-edd1-464b-a275-f53a30f21254
# ╟─d7328acf-75dd-4a74-93e3-56a493b8f72e
# ╟─ca251372-9a6f-409c-aa17-1349fa142f1a
# ╟─dfb56aac-626b-4655-9321-99ab2fc74cfe
# ╟─9c694aa7-2970-4de2-ada8-7ac34b4f37a2
# ╟─2b376666-65bc-47f7-90a7-35decb87078a
# ╟─8ce86785-261e-4c5d-a81b-27c2e519a8f6
# ╟─bbeb147a-2cb2-4177-958f-4d6b171cbb28
# ╠═e85d6f57-1d76-475f-ade0-fe85a82bc5ca
# ╠═0314ef45-6b1c-4738-aad1-e26e3cdfaa66
# ╠═dde18063-a566-4ba5-a918-5242eac54430
# ╟─a9694e3c-b208-4021-908e-f79ac3fd813a
# ╟─56bf6aa7-37e3-4ef8-afd7-c282289a8852
# ╟─73cdec6e-71cb-4c5a-9b2f-cee0f90a4812
# ╟─5c4efd0e-3db4-419e-b125-fa7a0645cef2
# ╟─bf16906f-f285-471d-97ed-6dc359404bf3
# ╟─af291ea0-b03c-4d77-aa75-670cd07a161d
# ╟─a8bba66f-719f-4254-bca0-64f41ea15e23
# ╠═e5ad7e3a-f912-45e9-9b15-add18ec3195a
# ╟─e1d04a77-a5d1-456d-8af5-f3e46678e0a1
# ╟─62e09a4f-3beb-4c2a-844f-76b32db8a9a8
# ╟─2b48bce0-8278-4542-9214-b6b6aa05857a
# ╟─25e7c7f4-c434-4ef7-a9dd-e10de282d3b8
# ╟─90dffbb7-8055-4d69-ac85-a2c7b511f024
# ╟─5b87a2e7-4c24-4504-b623-8647539780c5
# ╟─958392cf-a0c1-4feb-bdcd-9a3dd4efb8fd
# ╟─3214f857-a5d0-448b-aa77-5ccef8ae0f31
# ╟─4dc0b911-4ffc-4924-81f7-8a015ed5937a
# ╟─f394202b-de77-4f89-b79d-38747f8e77d3
# ╟─d861716d-b0c4-40f9-9fa2-5c8539480a18
# ╟─9d28361c-d3b4-44af-9a9c-d13d4f911f1f
# ╟─f8c559c3-8064-4f3c-a767-510eebc96d85
# ╟─88dfac9b-737d-4057-a1ea-db6ad61e22ef
# ╟─5a17bbf9-514f-4b2e-b8db-144c66f4af07
# ╠═18f78524-7836-4719-9c39-6999a3789125
# ╠═0d674fc4-d0a8-45a5-9c38-efd6e340fc54
# ╠═1bda23b8-b8c0-4ad2-83c8-1b322cf4a119
# ╠═a0cf81c4-a54e-4ee8-8813-3c1e989335cb
# ╟─f9e7768e-28a0-4c3a-b3df-5930a0ae097b
# ╠═c37c265d-57f9-41ec-9a85-f2cb90856cbf
# ╠═00ce55cc-27fa-4540-9983-e1d696bad2d1
# ╠═bfe09a62-2369-4f10-8898-1adfb46b275e
# ╠═12345a52-fde5-41eb-ac49-21eb5ac2ee16
# ╠═3bad4c86-867d-4e9c-99c5-9b316542a765
# ╠═1d3f9163-d52f-4f50-baf3-a24d327e7f7c
# ╟─c666b7b1-d810-43b3-85ee-77517f6ca409
# ╠═92a0edf6-8f8b-4daf-a3a3-135ff12fd492
# ╠═3f88433b-6256-428d-983b-e6fc6128efb5
# ╠═5ad49800-5dc0-4642-b374-afccb139cf83
# ╟─d572be50-93f1-4574-9afe-4320dfe517e2
# ╟─191009da-e7c3-484e-b15c-755012216902
# ╠═7b9e2ba5-3b8f-40a8-892d-862a361e0b93
# ╟─75e0a7e1-fa8b-4368-bfbd-5cd42bbb90ef
# ╟─8328d2d8-9ad5-4cf9-8006-30bf8b192e3e
# ╟─9477af88-edf1-4403-be5d-0fabc7e68c5a
# ╠═943e4e34-0e34-431b-8d5b-e6982af15e73
# ╟─768c1823-5659-40ca-9f38-afa2cdeea85a
# ╠═2878a88c-f60f-47dd-8814-dd17ea172ea6
# ╠═20c7819f-6d17-45b5-b317-b91ed5dc7715
# ╠═14256fdb-3da3-41b9-ad4f-17a51df2934c
# ╠═985d7745-19b2-4e39-84eb-9b12982d42a4
# ╠═0ccaefcd-fa8c-40c5-9dea-0600d4901add
# ╠═7f94c1eb-b316-4726-a84a-7c7b0e814b29
# ╠═8011d698-a78a-4371-bc57-49acc2bdd3b2
# ╠═86af3f0d-5ca1-408c-9a17-e041d415ca21
# ╠═b278cb84-febd-4e95-9f02-e2febc08e477
# ╠═494c685d-d18e-43fb-adcc-8b8907fcf229
# ╟─166429fb-6148-414d-b717-2a32c610c321
# ╠═8f50ab05-0053-46c5-97bc-751982cfc5f7
# ╠═cd353619-814e-4114-a0eb-ad77896b418a
# ╠═d5463e21-2f9d-4469-b51e-e349e4949f30
# ╠═f0d2d1e1-279d-4fa7-9005-8d404724663c
# ╠═47abef49-02ae-4bbf-9986-42629d25695f
# ╠═de3ddaaa-5ffb-4c24-959e-bcd60ca9d548
# ╠═9a00ece9-ddab-4206-9154-c0420d2bb801
# ╠═684f263a-78ef-4251-b589-089192e9ed9b
# ╠═bdfbb0ea-1f67-44fa-b74d-051c2aadee31
# ╠═d998e69b-852c-4a02-ae4f-2f4444fafbfd
# ╠═e030dc46-e87a-4429-8a61-3a51122b02b3
# ╠═021628d0-a170-4e9c-8079-f50722bb03b9
# ╠═85a0eb7e-3f79-46ee-a6fe-935e7ab7f331
# ╠═adbe0aea-37b2-4208-8a49-829408a286f2
# ╠═cf23420f-30e9-432f-8ef9-3fbd6498594d
# ╠═2776bc41-7d1d-4876-b281-e93ccba93733
# ╠═1592cd26-4c3a-4171-b306-e187b43f7258
# ╠═e42d7c0c-559e-4507-be56-c87414749d19
# ╠═0c69c9d1-4182-4e69-a1cc-14edd386ec24
# ╠═01d9a20d-5b08-47ff-b96d-3e8582d2cff5
# ╟─e969a627-d5bd-4595-a92c-2b855a2afd02
# ╟─d1a72462-9716-420a-ba54-dddb1c2fc562
# ╟─4cb19857-6643-4236-82f5-6f612e57c393
# ╟─5bc5e16f-36d1-4c78-a493-ac3013eb2891
# ╟─7ec19209-4590-466f-90f9-bf5a1b96e94e
# ╟─b598e525-81a5-4451-a891-6e3cea23762f
# ╟─5bbee908-beec-41c8-b4c4-c584a3791cd6
# ╟─ecb76401-1476-4d64-829d-9c211fbbabdb
# ╟─8f253d91-337f-4b8e-8664-bc76af44ed40
# ╟─deb0ddc7-3e9f-44e7-9d23-cd1f2125c960
# ╠═3d1e656a-502b-43d9-a0e5-ebae49794e34
# ╟─ddeaf1bf-afae-4663-b69e-da5634c54c2b
# ╟─1835dbf4-7c67-456e-b994-a2426184d08f
# ╠═a66678a3-59ab-43cc-8a0d-fdeb0770f3e6
# ╠═6e8389d6-8f04-443e-bcc8-0bebc6a96ee9
# ╟─1f38147d-6723-4aa1-81b6-d55b3533c63a
# ╟─7652d0e6-2c8a-4fc6-89e2-0d8efe4d127d
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
